### ISSUE TITLE
Search yields unexpected results

### ISSUE THREAD

**Issue by toehold** [ubports/address-book-app#78] opened 2019-02-28 16:11 UTC
Hi, using N5 Ubuntu 16.04 (2019-W09) I added 6 Contacts: A B, C D, E F, G H, I J and X Y; when I enter in the search field T or Z all contacts are shown which is not the case with other letters except: A,B,C,D,E,F,G,H,I,J,X and Y.
See also issue: https://github.com/ubports/address-book-app/issues/56

**Comment by mattbel10** [comment] 2019-03-01 19:17
I tried with the letter T (I don't have Z contacts) and I can confirm the issue.
Device: Meizu Pro5
Build: Ubuntu 16.04 (2019-W09)

**Comment by hummlbach** [comment] 2019-03-04 00:51
Mhmm, confirmed. I can't see any pattern here. Seems almost random. When filtering with only one letter, some contacts without the letter are filtered out, others not. Filtering by two or more letters seems to be plausible.

**Comment by lduboeuf** [comment] 2020-07-23 14:52
We should wait for branch https://github.com/ubports/address-book-app/tree/xenial_-_mercontacts being merged to see if this still an issue.
The issue there is that it does search within all "data" field in contact Detail, and there is one that have a date set, e.g "2020-06-28T21:15:24Z", that explain why T and Z retrieve contact even if no T and Z in contact's name

**Comment by UniversalSuperBox** [comment] 2022-01-06 16:25
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/78

**Closed by UniversalSuperBox** 2022-01-06 16:25 UTC
Labels: bug
