### ISSUE TITLE
Feature request: sorting contacts

### ISSUE THREAD

**Issue by idekovets** [ubports/address-book-app#61] opened 2018-11-20 08:01 UTC
By default contacts sorts: First name, Middle name, Last name.

Need function to change it.

I will see: Last name, First name, Middle name.

`Contacts sort:
- First name, Last name
- Last name, First name`

**Comment by Danfro** [comment] 2019-01-02 20:05
quite close a duplicate of #12

**Comment by hummlbach** [comment] 2019-01-19 18:35
@Danfro thanks for pointing that out. Closing it as duplicate.

**Closed by hummlbach** 2019-01-19 18:35 UTC
