### ISSUE TITLE
 Problems in the search function

### ISSUE THREAD

**Issue by Gabriele69** [ubports/address-book-app#56] opened 2018-10-16 09:39 UTC
with the latest updates, a problem has started with the search function.
When I open the "contacts" window from the phone or directly from the contacts app, the cursor is automatically positioned in the search bar (well! First this did not happen and I had to make an extra step)
But by typing the letters on the keyboard, the search does not work. You can not do the research.
Sometimes it happens that the cursor, instead, does not position itself directly on the search bar (rarely, I did not notice which combination causes it), in this case, after positioning the cursor, the search works perfectly
I use BQ 4.5 DEV last update

**Comment by resoli** [comment] 2018-10-16 20:30
I just installed and i'm under OTA5 on my krillin device. Same problems with the search. Manual browsing works. Searching contacts works from Messages app.

**Comment by pierrefrancois** [comment] 2018-10-24 09:03
Since update to OTA-5, same problem here on a BQ Aquaris 4.5 (krillin).

**Comment by hummlbach** [comment] 2018-10-27 22:16
I can confirm this. Something weird is going on there - sometimes the search works just fine and sometimes it silently does not filter the contacts. (For me the keyboard does never show up.)

**Comment by Danfro** [comment] 2018-11-09 17:01
I am having the same trouble with search on my BQ E5.
@hummlbach : Search does not bring up the keyboard as well. I did filed this as separate bug [#918](https://github.com/ubports/ubuntu-touch/issues/918) because this thread did not exist at that moment.
I found that search only works for the first time - mostly, not always.
Once I delete a few numbers or try a second search almost every time it does not work.
And sometimes I do not get favourites shown. Reported as well by David Gámiz Jiménez on the Supergroup TG thread today.

Because this thread covers more issues I will close #918.

**Comment by idekovets** [comment] 2018-11-20 07:55
I can confirm this. Search (in Russian) not work.
OTA-5 on Nexus 5

**Comment by hummlbach** [comment] 2018-11-26 07:38
Updated my pro5 (without wipe) to 16.04 rc channel on 2018-11-25. I'm not able to reproduce it there. Maybe a race condition somewhere.

**Comment by nikhilbhalwankar** [comment] 2018-12-04 09:34
Facing same problem for Contact Search function on BQ E5 HD.

**Comment by hummlbach** [comment] 2018-12-04 20:08
@lakota reported dev channel 637 was the last image with a properly working search function on the OPO.

**Comment by fourloop2002** [comment] 2018-12-06 21:41
Confirmed on N5 dev.  Did not work  on 737, updated to 740, open/closed Contacts app, still not working.  Search using Messaging app works.

**Comment by Danfro** [comment] 2018-12-07 21:17
Just had to flash my phone (no wipe) for other reasons. ;-)
The issue still remains [BQ E5, 16.04 rc 2018-W48].

**Comment by Anne017** [comment] 2018-12-09 18:06
This issue disappeared for me after the update to OTA 6 today, stable channel, on FP2.
Please try this to confirm if it fixes the problem.

**Comment by bastos77** [comment] 2018-12-15 13:03
Confirmed on FP2 rc Channelm 16.04 (2018-W50)

**Comment by nikhilbhalwankar** [comment] 2018-12-19 19:33
Requesting devs to please fix this issue on priority. Its a core functionality every phone needs all time.

**Comment by bastos77** [comment] 2018-12-20 09:06
still buggy on 2018-W51

**Comment by energius** [comment] 2018-12-25 00:56
The issue is still exist. Search in Contacts and in Phone app is do not work.
Device: Nexus 5
Build: Ubuntu 16.04 LTS -armhf (20181012)

Addition: In contact list exists Latin and Cyrillic names.

**Comment by Gabriele69** [comment] 2019-01-17 12:05
> Requesting devs to please fix this issue on priority. Its a core functionality every phone needs all time.

I confirm and agree. Also because the search by choosing the letters that appear scrolling through the list does not help at all. I should remember how I saved the contact because the letter refers to the first letter in the contact card.

**Comment by pierrefrancois** [comment] 2019-01-17 13:12
The problem here is that this bug has no assignee. If anybody knows how to fix it, he is welcome.

**Comment by bastos77** [comment] 2019-01-23 10:37
> Sometimes the filter stops being assigned correctly.

I can confirm, that sometimes it works and sometimes not.

**Comment by Danfro** [comment] 2019-01-23 16:35
Yep, search works not always. I would say most of the time, but not always.
But the OSK is not raised by default it I tap on search icon. OSK comes up only if I tap into the search field again.

**Comment by nikhilbhalwankar** [comment] 2019-02-11 04:15
If the issue is fixed, how to get the update on phone? Do I need to switch to RC channel?

**Comment by kugiigi** [comment] 2019-02-11 04:38
The PR for the fix is still open so it's not yet in any channel

**Comment by UniversalSuperBox** [comment] 2019-02-18 22:05
Closed by #74

**Closed by UniversalSuperBox** 2019-02-18 22:05 UTC
Labels: bug

**Comment by Gabriele69** [comment] 2019-02-20 14:56
Hi. I update my phone this morning (20/02/2019 RC Channel 16.04 2019W08). The issue is fixed ! Thank You to all developer !!

**Comment by toehold** [comment] 2019-02-28 07:59
Hi, using N5 Ubuntu 16.04 (2019-W09) I added 6 Contacts: A B, C D, E F, G H, I J and X Y; when I enter in the search field T or Z all contacts are shown which is not the case with other letters except: A,B,C,D,E,F,G,H,I,J,X and Y.

**Comment by UniversalSuperBox** [comment] 2019-02-28 15:54
@toehold, I was able to reproduce that problem. I think it is another, separate bug, though. Could you file a new report here on address-book-app?

**Comment by jezek** [comment] 2019-02-28 16:04
FP2 (2019-W09)

- opening contacts search from launcher (open messaging-app and then tap search button). The search field is shown, but not focused and the OSK doesn't pop up. Need to tap the search field for osk.
- opening contacts search from phone app. The search field is shown and focused, the OSK is shown.
- opening contacsts search from messaging app (start new message, tap + to add recipient). Search is not shown. Need to tap the search button, then search field is shown and focused, OSK is sown
- contacts search in telefram app (hamburger menu -> contacts). Just sows contacts. When tapping search, search is shown, not focused. After search field tap, OSK pops out. (here search result al always right, but can't search some string inside names)

The searching alone is not always right and consistent. Sometimes I get for the same search term only relevant results, sometimes all contacts. If the search string is only 1 letter long (eg "x"), all contacts are shown.

**Comment by kugiigi** [comment] 2019-02-28 16:10
I would suggest trying out your findings in the stable channel and compare. They might be a separate issue that should logged separately. I was also able to replicate the issue on my MX4 in OTA 7

**Comment by jezek** [comment] 2019-02-28 16:40
@kugiigi I was not sure, what was this bug about and if it is fixed (the first post was about cursor positioning, or search results fails?). So I posted my current findings as detailed as I thought was enough, so the person with more insights can deduce if it is fixed or not. ;)

Note: This a a response for OTA-8 testing call.

**Comment by Danfro** [comment] 2019-02-28 17:55
I had filed @jezek  s problem with the search not opening the OSK already as [#918](https://github.com/ubports/ubuntu-touch/issues/918) but closed it because I thought it to be a duplicate.
Now it seems that this is not the case. Reopend as [#79](https://github.com/ubports/address-book-app/issues/79).

**Comment by ziggutas** [comment] 2019-03-01 10:25
Nexus 7 (flo), rc, 2019-W09. Search works but cursor and OSK not present when opening app until one tap in the search bar brings them up.

**Comment by ziggutas** [comment] 2019-03-01 10:27
#79

**Comment by mattbel10** [comment] 2019-03-01 19:33
I cannot reproduce anymore the described issue, therefore it is fixed thanks to @dobey. 

Device: Meizu Pro5
Build: Ubuntu 16.04 (2019-W09)

**Comment by erik-kueng** [comment] 2019-03-02 09:51
FP2
2019-W09
search works in contacts and phone-app, but not in massage-app

**Comment by ziggutas** [comment] 2019-03-02 16:20
BQ E4.5 2019-W09
Open phone app and search contacts works as expected.

Open contacts and search will work but initially the cursor and osk are not present. Single tap in search box brings them up.

Restart device, open contacts for the first time and search works as expected. Open contacts second and subsequent times and again the cursor & osk not present until search box tapped.
Two more restarts produced the same results.
