### ISSUE TITLE
Wrong button colors when removing contact

### ISSUE THREAD

**Issue by cibersheep** [ubports/address-book-app#64] opened 2018-12-16 21:10 UTC
When removing a contact, button colors are inverted.

Question: Do you want to remove contact?
Answer: yes (negative action. Should be red)
Answer: no (neutral answer. Could be ash)

**Comment by advocatux** [comment] 2019-01-01 19:53
Device: Nexus 5 (hammerhead)
Channel: RC
Version: `2018-W01` (_really_ `2019-W01`)

I don't know which color combination would be better, or the "correct" one for that matter, but I can confirm that it's still happening the way Joan describes: 'green' for 'Yes', 'red' for 'No'.

**Comment by cibersheep** [comment] 2019-01-02 03:33
Devices: Cooler and Vegeta
Channel: RC
2018-W01

Color combination still green for "Yes" and red for "No".
`sudo ubpots-qa update` made no difference.

**Comment by erik-kueng** [comment] 2019-01-02 18:52
Fairphone 2
rc 
2018-W01

Yes is green. No is red

**Comment by NeoTheThird** [comment] 2019-01-03 17:02
I can confirm that #65 did not fix this, yes is still green, no still red.

Opinion: I find this counter-intuitive. From my understanding, even though deleting a contact is a negative action, clicking yes is a positive action, because you give positive confirmation to a previous action (whatever that might be). Would it not be better to have the "do you really want to" dialogs exactly the same everywhere accross the ui? In any case, it might be a good idea to make a decision on wether confirmation dialogs are a separate action or inherit the positivity or negativity of the action pending confirmation.

**Comment by cibersheep** [comment] 2019-01-03 18:59
Interesting. Green as a «yes» go and delete it?
For now we have been using «wrong» the colors: yes/ok is always green and cancel is always red.
It «should be» gren/red/blue (depending on if they're destructive, safe or neutral) as the main option and grey the other options.

Going further, we could change the question:
Question: Do you want to remove contact?
Answer: Delete (negative action. Should be red)
Answer: Cancel (neutral answer. Could be ash)

**Comment by UniversalSuperBox** [comment] 2019-01-05 03:05
Ah, I see what happened here. address-book-app is a deb, so a PR should be made to `xenial` to land it in the image.

I'd say that since this happened, the language change to the dialog would be a good idea for OTA-8.

**Comment by cibersheep** [comment] 2019-01-06 00:04
I see... silly me and my not-know-what-a-branch-is syndrome:
https://github.com/ubports/address-book-app/pull/70

**Comment by UniversalSuperBox** [comment] 2019-02-18 22:05
Fixed by #70

**Closed by UniversalSuperBox** 2019-02-18 22:05 UTC

**Comment by toehold** [comment] 2019-02-28 08:09
I get a Red Button saying: Remove and a grey Cancel Button. Ubuntu 16.06 (2019-W09)

**Comment by jezek** [comment] 2019-02-28 15:36
FP2 (2019-W09)
- remove button **red**
- cancel button **gray**

**Comment by Danfro** [comment] 2019-02-28 22:05
as above remove = red, cancel = gray on E5 running RC 2019-W09

**Comment by ziggutas** [comment] 2019-02-28 22:44
Nexus 7 (flo), rc2019-W09. Red for remove, Grey to cancel.
